In [1]:
import numpy as np
from scipy import linalg as LA

In [2]:
A = np.array([[4.0,3.0],[2.0,2.0],[-1.0,-3.0],[-5.0,-2.0]])
U , S , Vt = LA.svd(A)
print(U)
print(S)
print(Vt)
X = np.array([0.243,0.97])
X = X/LA.norm(X)
P = np.dot(Vt, X)
print(P)
S = LA.diagsvd(S,4,2)
Q = S@P
print("Q values",Q)
y= U@Q
print("values of y",y)
print("product of A*X",A@X)

[[-0.61215255 -0.05228813  0.06420835  0.78639208]
 [-0.34162337 -0.2025832   0.84891247 -0.34871356]
 [ 0.31300005  0.80704816  0.42637948  0.26249717]
 [ 0.64077586 -0.55217683  0.30565577  0.4371288 ]]
[8.16552039 2.30743942]
[[-0.81424526 -0.58052102]
 [ 0.58052102 -0.81424526]]
[-0.7609864  -0.64876784]
Q values [-6.21384993 -1.49699248  0.          0.        ]
values of y [ 3.88209899  2.42606187 -3.1530804  -3.15508046]
product of A*X [ 3.88209899  2.42606187 -3.1530804  -3.15508046]
